name: Flutter CI

on:
  push:
    branches:
      - main
      - "devops/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Installation de Java (Requis pour les outils Android)
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # Utilise toujours la version stable la plus récente

      - run: flutter --version

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - run: flutter pub get

      #  - run: flutter analyze

      # On lance les tests (pour l'instant tu n'en as pas, mais ça prépare le terrain)
      - run: flutter test
